mod "boxen",      "3.6.2.xdissent", :github_tarball => "xdissent/puppet-boxen"
mod "repository", "2.2.0", :github_tarball => "boxen/puppet-repository"
mod "stdlib",     "4.0.0", :github_tarball => "puppetlabs/puppetlabs-stdlib"
